# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ncag.info
email: pieter.belmans@uni.lu
description: a website for things related to noncommutative algebraic geometry
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ncag.info" # the base hostname & protocol for your site
twitter_username: ncaginfo

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/archive/:num/"
gems: [jekyll-paginate]
